### ISSUE TITLE
macOS Catalina 10.16 issue 

### ISSUE THREAD

**Issue by erdemy** [openimaj/openimaj#170]
as we are using https://github.com/sarxos/webcam-capture library which . uses openimaj in default,  it does not work with macOS Catalina.
as QTKit is deprecated, AvFoundation classes need to be used. may i ask if there is any ongoing work for this kind of change?

regards,

**Comment by jonhare** [comment]
Ah, I didn't know about this - it's going to a a big priority for my teaching in 4-5 weeks  time! I got most of the code converted last night, although it's not working yet (need to spend some time to debug why the delegate isn't being called). Will keep you posted.

**Comment by erdemy** [comment]
thanks @jonhare for the quick reply and conversion. I can help with the Java JNI part if you can share the branch name.
regards

**Comment by jonhare** [comment]
OK,  this should be fixed in 940ed45024bc4f83318ec1d296752ef15a7e2cb0, although it clearly needs testing. A snapshot is being built now (http://jenkins.ecs.soton.ac.uk/job/OpenIMAJ/5457/) and will be deployed to snapshots.openimaj.org immediately afterwards (assuming Jenkins builds without any problems!).

@erdemy any chance you can try the snapshot version of the jar in your project and see  if it works for you?

**Comment by erdemy** [comment]
@jonhare thanks for very quick action, glad to test the jar file, will update here with the results

**Comment by ademzumbul** [comment]
![image](https://user-images.githubusercontent.com/31505025/63951622-c02b4380-ca86-11e9-9aa8-0b2852ac0670.png)

New version of the libray compiles fine on Catalina, it can bring list of camera, but I am having error when running on TestGrabber, it says No factory registered, what can be the reason ?

**Comment by jonhare** [comment]
Hmm, I'm not sure: On Mojave it works fine for me, although it does print some CMIO warnings:

```
FaceTime HD Camera
2019-08-29 16:33:18.291326+0100 TestGrabber[17265:2502741] [] CMIO_Unit_ScopeElement.h:200:SafeGetElement Throwing err: -67454
2019-08-29 16:33:18.293496+0100 TestGrabber[17265:2502741] [] CMIOUnitFigBaseObjectImpl.c:246:CMIOUnitCreateFromDescription Invalid paramater
2019-08-29 16:33:18.316681+0100 TestGrabber[17265:2502741] [] CMIO_Unit_Input_Device.cpp:244:GetPropertyInfo CMIOUInputFromProcs::GetPropertyInfo() failed for id 102, Error: -67456
dev 0 : 0x107e2c000
done
dev 0 : 0x107e2c000
done
dev 0 : 0x107e2c000
done
dev 0 : 0x107e2c000
done
...
```

Any chance you can step through the `startSession` call  in the debugger to try and see where it is returning from? That would help isolate the problem...

**Comment by ademzumbul** [comment]
It looks the warnings are printed here:

![image](https://user-images.githubusercontent.com/31505025/63966929-05f70480-caa5-11e9-8693-0d9d520df0c5.png)

**Comment by ademzumbul** [comment]
After getting the above warning, it looks in my case session cannot be created due to authorization:

![image](https://user-images.githubusercontent.com/31505025/63967588-6aff2a00-caa6-11e9-9885-a2539fed5b5b.png)

Do you know how to authorize it? I already allowed TestGrabber in Security settings:

![image](https://user-images.githubusercontent.com/31505025/63967767-bdd8e180-caa6-11e9-9701-43f875168235.png)

**Comment by ademzumbul** [comment]
It looks in my case authorization status is 0 which means user hasnt done a choise, but not sure how to do it?

![image](https://user-images.githubusercontent.com/31505025/63968032-5b341580-caa7-11e9-8625-e187cce5ed40.png)

**Comment by jonhare** [comment]
Two thoughts: 1.) you could try copying the info.plist file to the directory in which the TestGrabber executable is built & see if that makes a difference when running it; 2)  you could try running 'tccutil reset Camera' and see if that makes a difference. In principle it  should display a dialog box asking for permission...

I think I will change the logic in the code so that it doesn't fail in `startSession` if authorisation has not yet been granted - the documentation says that the system should  just deliver blank frames until the user grants access anyway...

**Comment by erdemy** [comment]
Hi @jonhare, tested on macOS Mojave and it is working great.  but when i test it on Catalina, i got the following error:
```
Caused by: java.lang.UnsatisfiedLinkError: org.openimaj.video.capture.OpenIMAJGrabber.getVideoDevices()Lorg/bridj/Pointer;
	at org.openimaj.video.capture.OpenIMAJGrabber.getVideoDevices(Native Method)
	at org.openimaj.video.capture.VideoCapture.getVideoDevices(VideoCapture.java:221)
	at com.github.sarxos.webcam.ds.openimaj.OpenImajDriver$GetDevicesTask.handle(OpenImajDriver.java:58)
	at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)
```
will investigate more on weekend.

**Comment by ademzumbul** [comment]
Hi @jonhare , I have done 2 things:
1-) run 'tccutil reset Camera' on console 
2-) commented out "return 1" statement if startSession fails, so program continues althoug startSession fails

So now MacOS asks permission when taking picture and I can grant overthere, and it works that way.
But still something is random, so it cannot open camera in my every try. So it will be better if you can check this example in Catalina on your side.

**Comment by ademzumbul** [comment]
@jonhare, have you done any changes in the sources about the permission issue ?

**Comment by jonhare** [comment]
@ademzumbul I made changes so that it didn't exit if permission hadn't been granted, but that's it. On Mojave it seems ok to me - asks permission the first time & then just works afterwards.

**Comment by ademzumbul** [comment]
@jonhare, ok, i will try the new version of the library and let you know if permission issue works on Catalina

**Comment by ademzumbul** [comment]
@jonhare I have tested new version on MacOS Catalina, it works fine, this time it asks permission every time i start raw application and after that it can grab from camera. Thanks for your help.

**Comment by jonhare** [comment]
__UPDATE__: So, I'm reasonably happy the permission issue is fixed. The Catalina issue remains & I've spent the last few hours trying to isolate what is going on. I don't yet have a fix, but I have a work-around.

Workaround: put the `libOpenIMAJGrabber.dylib` somewhere (say in `/path/to/directory`) and then set the DYLD_LIBRARY_PATH environment variable to that directory before launching java. For example: `DYLD_LIBRARY_PATH=path/to/directory java -jar my.jar`

I'm still not quite sure what is going on or why that fixes things. It is clear that the problem stems from within the `Bridj` and `dynload` libraries that are used to load the native library. More specifically `JNI.loadLibrarySymbols` in Bridj is returning 0, which would seem to indicate that the dynload `dlSymsInit` is returning `NULL`. I confirmed this separately through a simple C program that when linked against the latest `dynload` release works correctly, but when linked against the native `bridj.dylib` fails.

**Comment by jonhare** [comment]
Ok, I ended up building a new version of the bridj jar with a new osx native library in it (which uses a non-broken dynlib). I've deployed this to maven.openimaj.org and also updated openimaj to use it rather than the older version. A new SNAPSHOT build should be available momentarily (http://jenkins.ecs.soton.ac.uk/job/OpenIMAJ/5463/). 

@erdemy any chance you can test this works for you please? I've tested on both Catalina and High Sierra & it seems fine on both for me.

**Comment by kkieffer** [comment]
Any additional progress here? Like @erdemy I am also blocked on Catalina using https://github.com/sarxos/webcam-capture.  I have tried copying the SNAPSHOT build's .dylib into webcam-capture and building it from source, but I get a "device error" on both Mojave and Catalina.

**Comment by jonhare** [comment]
As I said above, as far as I am aware all the issues have now been solved in the current snapshot version - I used that version for teaching last semester and I'd guess it was used by 50+ people on differing OSX versions... A simple test is to run the face detection example jar: https://github.com/jonhare/SimpleFaceDetector/releases/download/v1.1/SimpleFaceDetector-1.1-tool.jar

**Comment by kkieffer** [comment]
Great thanks for sending that jar. I confirmed it works both on Mojave and Catalina. And prompts for access to the camera too. Can you push a release for this? It looks like commit 7f8b98497 is needed beyond 1.3.9.

**Comment by jonhare** [comment]
Done - OpenIMAJ-1.3.10 is now on maven central and maven.openimaj.org. I'll update the website  shortly.

**Comment by jingmingcn** [comment]
@jonhare The face detection executable jar works on my macOS Catalina 10.15.4. But when I run the SimpleFaceDetector class directly in the IDE(I have tried both eclipse and IntelliJ IDEA), this following error message keeps coming.
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'org.bridj.Pointer org.openimaj.video.capture.OpenIMAJGrabber.getVideoDevices()' 
at org.openimaj.video.capture.OpenIMAJGrabber.getVideoDevices(Native Method) 
at org.openimaj.video.capture.VideoCapture.getVideoDevices(VideoCapture.java:221) 
at gist.SimpleFaceDetector.liveMode(SimpleFaceDetector.java:49) 
at gist.SimpleFaceDetector.main(SimpleFaceDetector.java:165)
```

The maven dependencies are:
```
<dependency>
    <groupId>org.openimaj</groupId>
    <artifactId>core-video-capture</artifactId>
    <version>1.3.10</version>
</dependency>
<dependency>
    <groupId>org.openimaj</groupId>
    <artifactId>faces</artifactId>
    <version>1.3.10</version>
</dependency>
```
I also tried the version `1.4-SNAPSHOT`, and I got the same error message. So I wonder what's the trick in the Jar file you provided. Or is there any solution or any reason, which can solve or cause the error.

**Comment by jonhare** [comment]
@jingmingcn no idea - I just took a clean checkout of the SimpleFaceDetector project, imported it into Eclipse (as a maven project) and ran the SimpleFaceDetector.java file. It runs without any problems for me. 

Only thing I can suggest would be to ensure that all the transitive dependencies are indeed downloaded - try building the SimpleFaceDetector jar from the command-line perhaps and check that it runs there.

**Comment by jingmingcn** [comment]
@jonhare 

Thanks for your quick reply. Here is an update about the test case.

I just test your solution on my another `macOS 10.14.6 (aka. Mojave)`, and it turns out works great. So considering the situation of failure running on my `macOS Catalina 10.15.4`, I can give the conclusion that, the `OpenIMAJGrabber.getVideoDevices()` method fails on the newest macOS version.

I think there was an update about this camera permission request situation on the `macOS Catalina 10.15.2`, which has fixed the problem early. And the camera access permission not granted issue was just reopened on `macOS Catalina 10.15.4`.

But I am still wondering why the `face detector Jar file` works very well on `macOS Catalina 10.15.4`. Maybe that's because of the very formal and official `groupId` and the `artifactId`, or Maybe there are some labels or information got the trust of the system.

This problem has confused me for days, and I hope there will be some advice from you.

**Comment by jingmingcn** [comment]
@jonhare 

Here are some updates about this issue I hope will help you to figure out the cause. 

The following message is from the `macOS Catalina 10.15.4` built-in `Console.app` with the process name `syspolicyd `

```
assessment denied for libOpenIMAJGrabber.dylib
com.apple.message.domain: com.apple.security.assessment.outcome2
com.apple.message.signature2: bundle:UNBUNDLED
com.apple.message.signature3: libOpenIMAJGrabber.dylib
com.apple.message.signature5: UNKNOWN
com.apple.message.signature4: 1
com.apple.message.signature: denied:no usable signature
SenderMachUUID: 821D8C33-5B0B-317C-B2CB-29137C319A18
```

The thread I have already posted under the `webcam-capture` project issue list. [Link](https://github.com/sarxos/webcam-capture/issues/723#issuecomment-606679227)

**Comment by jingmingcn** [comment]
@jonhare  Here is the update.

By explicitly declaring an environment variable name `DYLD_LIBRARY_PATH` to a folder contains the `libOpenIMAJGrabber.dylib` file in the IDE, the face detector code works.

**Comment by TomZwicky** [comment]
Hi, the sample provided does not run on my Mac Catalina. No output, just aborting.

Btw: I am using OpenImaJ with Webcam Capture for Raspberry and would love to have it on my Mac, too.

Downloaded file from https://github.com/jonhare/SimpleFaceDetector/releases/download/v1.1/SimpleFaceDetector-1.1-tool.jar

%java -jar SimpleFaceDetector-1.1-tool.jar 
zsh: abort      java -jar SimpleFaceDetector-1.1-tool.jar

% java -version
java version "14.0.1" 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

**Comment by TomZwicky** [comment]
@kkieffer Anything special to do to get the JAR running? I download and run on Catalina 10.15.4, but JAVA process just aborts. I tried tccutil to rest Camera permissions, did not help. Rebooted, same abort, running Java 8 update 251

**Comment by kkieffer** [comment]
@TomZwicky suggest you read this thread https://github.com/sarxos/webcam-capture/issues/723
