### ISSUE TITLE
ASIFT Matching Error

### ISSUE THREAD

**Issue by akram-trigyn** [openimaj/openimaj#177]
Hi,
Getting this error when trying to compare 2 images. Attaching the images which i am trying to compare.
I also increased the heap size then also it is not working as expected.
With other smaller image it is working fine
[11](https://user-images.githubusercontent.com/46591048/65942219-75686700-e44a-11e9-9bdb-0246e3259086.jpg)

![1](https://user-images.githubusercontent.com/46591048/65942220-7600fd80-e44a-11e9-84b2-d35867c116f3.jpg)

`Extracted input1: 30814
Extracted input2: 31086
Oct 01, 2019 12:51:52 PM com.github.fommil.netlib.LAPACK <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeSystemLAPACK
Oct 01, 2019 12:51:52 PM com.github.fommil.jni.JniLoader liberalLoad
INFO: successfully loaded C:\Users\SATISH~1.PAN\AppData\Local\Temp\jniloader8556948455129610778netlib-native_ref-win-x86_64.dll
Exception in thread "main" java.lang.IllegalArgumentException: Matrix of 57890 x 57890 = 3351252100 elements is too large to be allocated using a single Java array.
	at no.uib.cipr.matrix.AbstractDenseMatrix.<init>(AbstractDenseMatrix.java:53)
	at no.uib.cipr.matrix.DenseMatrix.<init>(DenseMatrix.java:167)
	at no.uib.cipr.matrix.SVD.<init>(SVD.java:97)
	at no.uib.cipr.matrix.SVD.<init>(SVD.java:75)
	at no.uib.cipr.matrix.SVD.factorize(SVD.java:149)
	at org.openimaj.math.matrix.MatrixUtils.solveHomogeneousSystem(MatrixUtils.java:1549)
	at org.openimaj.math.matrix.MatrixUtils.solveHomogeneousSystem(MatrixUtils.java:1522)
	at org.openimaj.math.geometry.transforms.TransformUtilities.homographyMatrix(TransformUtilities.java:821)
	at org.openimaj.math.geometry.transforms.HomographyModel.estimate(HomographyModel.java:139)
	at org.openimaj.math.model.fit.RANSAC.fitData(RANSAC.java:529)
	at org.openimaj.math.geometry.transforms.estimation.RobustHomographyEstimator.fitData(RobustHomographyEstimator.java:172)
	at org.openimaj.feature.local.matcher.consistent.ConsistentLocalFeatureMatcher2d.findMatches(ConsistentLocalFeatureMatcher2d.java:138)
	at com.example.schedulerdemo.ASIFTMatchingExample.main(ASIFTMatchingExample.java:68)
`

**Comment by akram-trigyn** [comment]
![11](https://user-images.githubusercontent.com/46591048/65942414-e1e36600-e44a-11e9-98a6-5367e43a1ae7.jpg)

**Comment by akram-trigyn** [comment]
@jonhare can you please let me know,if there is any solution for larger images

**Comment by akram-trigyn** [comment]
used this to resolve this issue. closing it.
`ResizeProcessor.resizeMax(image2,` 1024)`
