### ISSUE TITLE
FlickrImageDataset has problems with JPEG images

### ISSUE THREAD

**Issue by OscarVanL** [openimaj/openimaj#180]
I'm completing [Chapter 6 of the tutorial](http://openimaj.org/tutorial/image-datasets.html), this has the following dataset generation from online sources example:

```
FlickrAPIToken flickrToken = DefaultTokenFactory.get(FlickrAPIToken.class);
FlickrImageDataset<FImage> cats = 
		FlickrImageDataset.create(ImageUtilities.FIMAGE_READER, flickrToken, "cat", 10);
DisplayUtilities.display("Cats", cats);
```

Running this gives the following exception:
```
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: org.apache.sanselan.ImageReadException: Sanselan cannot read or write JPEG images.
	at org.openimaj.image.dataset.FlickrImageDataset.read(FlickrImageDataset.java:237)
	at org.openimaj.image.dataset.FlickrImageDataset.access$100(FlickrImageDataset.java:68)
	at org.openimaj.image.dataset.FlickrImageDataset$1.next(FlickrImageDataset.java:260)
	at org.openimaj.image.dataset.FlickrImageDataset$1.next(FlickrImageDataset.java:250)
	at org.openimaj.image.DisplayUtilities.display(DisplayUtilities.java:1687)
	at uk.ac.soton.ecs.ojvl1g17.ch6.App.main(App.java:51)
Caused by: java.io.IOException: org.apache.sanselan.ImageReadException: Sanselan cannot read or write JPEG images.
	at org.openimaj.image.ExtendedImageIO.read(ExtendedImageIO.java:189)
	at org.openimaj.image.ImageUtilities.readF(ImageUtilities.java:329)
	at org.openimaj.image.ImageUtilities$1.read(ImageUtilities.java:75)
	at org.openimaj.image.ImageUtilities$1.read(ImageUtilities.java:72)
	at org.openimaj.image.dataset.FlickrImageDataset.read(FlickrImageDataset.java:235)
	... 5 more
Caused by: org.apache.sanselan.ImageReadException: Sanselan cannot read or write JPEG images.
	at org.apache.sanselan.formats.jpeg.JpegImageParser.getBufferedImage(JpegImageParser.java:90)
	at org.apache.sanselan.Sanselan.getBufferedImage(Sanselan.java:1264)
	at org.apache.sanselan.Sanselan.getBufferedImage(Sanselan.java:1163)
	at org.apache.sanselan.Sanselan.getBufferedImage(Sanselan.java:1136)
	at org.openimaj.image.ExtendedImageIO.read(ExtendedImageIO.java:187)
	... 9 more

```

**Comment by jonhare** [comment]
This can happen when Flickr serves you a non-compliant JPEG (or potentially if there is a network glitch). In order for that specific exception to be thrown, the three different jpeg loading libraries will have already been tried: JAI, ImageIO with the TwelveMonkeys jpeg reader, and the system ImageIO jpeg reader. Dealing with content loaded from the web is hard - there isn't really a lot else we can do in the library; of course its not so difficult for user code to catch the exceptions when iterating and just skip images (or do something else). 

In the particular case of the Flickr dataset,  there are enough images of cats being uploaded at any given point that you should be able to run it again after a few moments and not be served a broken image. You could also change the query.

**Comment by OscarVanL** [comment]
Ok, thank you :)
