### ISSUE TITLE
ArrayIndexOutOfBoundsException in VideoCapture:main()

### ISSUE THREAD

**Issue by jonhare** [openimaj/openimaj#19]
OP-20: I created sample application from Maven archetype, commented whole code in App.java and added this line only:

{code}
VideoCapture.main(null);
{code}

New window is open, but it's empty. In console I see:

{code}
Not enough args for boolean OpenIMAJGrabber.startSession(int, int, double)
Device[0]="HP HD Webcam [Fixed]"
Exception in thread "Thread-3" java.lang.ArrayIndexOutOfBoundsException: 960
	at org.openimaj.video.capture.VideoCapture.getNextFrame(VideoCapture.java:190)
	at org.openimaj.video.capture.VideoCapture.getNextFrame(VideoCapture.java:49)
	at org.openimaj.video.VideoDisplay.run(VideoDisplay.java:134)
	at java.lang.Thread.run(Thread.java:662)

***** VIDEOINPUT LIBRARY - 0.1995 - TFW07 *****

VIDEOINPUT SPY MODE!

SETUP: Looking For Capture Devices
SETUP: 0) HP HD Webcam [Fixed] 
SETUP: 1 Device(s) found

***** VIDEOINPUT LIBRARY - 0.1995 - TFW07 *****

VIDEOINPUT SPY MODE!

SETUP: Looking For Capture Devices
SETUP: 0) HP HD Webcam [Fixed] 
SETUP: 1 Device(s) found

SETUP: Setting up device 0
SETUP: HP HD Webcam [Fixed]
SETUP: Couldn't find preview pin using SmartTee
SETUP: Default Format is set to 640 by 480 
SETUP: trying format RGB24 @ 960 by 720
SETUP: trying format RGB32 @ 960 by 720
SETUP: trying format RGB555 @ 960 by 720
SETUP: trying format RGB565 @ 960 by 720
SETUP: trying format YUY2 @ 960 by 720
SETUP: trying format YVYU @ 960 by 720
SETUP: trying format YUYV @ 960 by 720
SETUP: trying format IYUV @ 960 by 720
SETUP: trying format UYVY @ 960 by 720
SETUP: trying format YV12 @ 960 by 720
SETUP: trying format YVU9 @ 960 by 720
SETUP: trying format Y411 @ 960 by 720
SETUP: trying format Y41P @ 960 by 720
SETUP: trying format Y211 @ 960 by 720
SETUP: trying format AYUV @ 960 by 720
SETUP: trying format Y800 @ 960 by 720
SETUP: trying format Y8 @ 960 by 720
SETUP: trying format GREY @ 960 by 720
SETUP: couldn't find requested size - searching for closest matching size
SETUP: closest supported size is RGB24 @ 1280 720
SETUP: Capture callback set
SETUP: Device is setup and ready to capture.
{code}

Let me know if you need anything else.

**Comment by jonhare** [comment]
Original reporter: @sarxos

**Comment by jonhare** [comment]
sarxos:  Components should be core/core-video

**Comment by jonhare** [comment]
davedupplaw:  Ok, I updated the module to be core/core-video.  That assigns it to Sina :)

**Comment by jonhare** [comment]
sarxos:  Thank you David,


Sina,

Maybe you could also take a look an this:

{code}
Not enough args for boolean OpenIMAJGrabber.startSession(int, int, double)
{code}

It appears *always* when I initialize VebcamCapture. It doesn't matter what number of arguments I'm passing - effect is always the same (I tried only with size parameters, then added device argument and FPS too, no effect).

**Comment by jonhare** [comment]
jonhare:  The "Not enough args for boolean OpenIMAJGrabber.startSession(int, int, double)" is a random println in Bridj, the library that we use to link to the native code; it doesn't actually indicate a problem. This should be removed for the next release.

UPDATE: Improvement requested in Bridj: https://github.com/ochafik/nativelibs4java/issues/328

**Comment by jonhare** [comment]
sinjax:  Hey Bartosz,

We've been doing a lot of work on OpenIMAJ since 1.0.5 and we're actually almost ready for a 1.1 release.
However until then could you please try the 1.0.6-SNAPSHOT libraries instead of the 1.0.5.

Instructions on how to do this can be found here: http://blogs.ecs.soton.ac.uk/multimedia/2012/07/09/openimaj-maven/

Tell me what results you get

Cheers,
- Sina

**Comment by jonhare** [comment]
sarxos:  Sina,

Effect is the same. The good news is that I do not have so many logs from natives :D

{code}
Device[0]="HP HD Webcam [Fixed]"
Exception in thread "Thread-4" java.lang.ArrayIndexOutOfBoundsException: 960
	at org.openimaj.video.capture.VideoCapture.getNextFrame(VideoCapture.java:246)
	at org.openimaj.video.capture.VideoCapture.getNextFrame(VideoCapture.java:50)
	at org.openimaj.video.VideoDisplay.run(VideoDisplay.java:169)
	at java.lang.Thread.run(Thread.java:662)
{code}

**Comment by jonhare** [comment]
jonhare:  Ok, I can get the same problem here on a Win7 VM if I'm using an HD camera. 

There's definitely a bug in the startSession methods of the VideoCapture class, as it's not properly listening to the size of the image the camera returns. On linux & osx, the native code will always [I think; at least never seen otherwise] return the image at the size you request, however, the windows code returns the frames at the "best fit" size, which might be different to what was requested. I'll commit a fix shortly.

**Comment by jonhare** [comment]
jonhare:  Fix for the size issue in commit 1214. Also changed the main method to do something more intelligent and not choose a resolution that is unlikely to be supported. Tested on a Win7 VM with a range of resolutions.

**Comment by jonhare** [comment]
jonhare:  Fixed in commit 1214.
