### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: odk/lang/FastMath

### ISSUE THREAD

**Issue by jonhare** [openimaj/openimaj#26]
OP-27: I ran the tutorial:

import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.openimaj.feature.local.list.LocalFeatureList;
import org.openimaj.feature.local.matcher.BasicMatcher;
import org.openimaj.feature.local.matcher.LocalFeatureMatcher;
import org.openimaj.feature.local.matcher.MatchingUtilities;
import org.openimaj.image.DisplayUtilities;
import org.openimaj.image.ImageUtilities;
import org.openimaj.image.MBFImage;
import org.openimaj.image.colour.RGBColour;
import org.openimaj.image.feature.local.engine.DoGSIFTEngine;
import org.openimaj.image.feature.local.keypoints.Keypoint;

public class AnalizadorDeImagenes {

    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        
        MBFImage query = null;
        MBFImage target = null;
                 
        try {
            query = ImageUtilities.readMBF(new File("C:\\novovia\\DetectorDePatentes\\query.png"));
        } catch (IOException ex) {
            Logger.getLogger(AnalizadorDeImagenes.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            target = ImageUtilities.readMBF(new File("C:\\novovia\\DetectorDePatentes\\origen.png"));
        } catch (IOException ex) {
            Logger.getLogger(AnalizadorDeImagenes.class.getName()).log(Level.SEVERE, null, ex);
        }

        

        DoGSIFTEngine engine = new DoGSIFTEngine();
        LocalFeatureList<Keypoint> queryKeypoints = (LocalFeatureList<Keypoint>) engine.findFeatures(query.flatten());
        LocalFeatureList<Keypoint> targetKeypoints = (LocalFeatureList<Keypoint>) engine.findFeatures(target.flatten());

        LocalFeatureMatcher<Keypoint> matcher = new BasicMatcher<Keypoint>(80);

        matcher.setModelFeatures((List<Keypoint>) queryKeypoints);
        matcher.findMatches((List<Keypoint>) targetKeypoints);

        MBFImage basicMatches = MatchingUtilities.drawMatches(query, target, matcher.getMatches(),RGBColour.RED);

        DisplayUtilities.display(basicMatches);
        
        

    }

}

and I'm receiving the following message:

run:
Exception in thread "main" java.lang.NoClassDefFoundError: odk/lang/FastMath
        at org.openimaj.image.processing.convolution.FImageGradients.gradientMagnitudesAndOrientations(FImageGradients.java:126)
        at org.openimaj.image.feature.local.detector.dog.extractor.GradientFeatureExtractor.getCurrentGradientProps(GradientFeatureExtractor.java:149)
        at org.openimaj.image.feature.local.detector.dog.extractor.GradientFeatureExtractor.extractFeature(GradientFeatureExtractor.java:112)
        at org.openimaj.image.feature.local.detector.dog.extractor.GradientFeatureExtractor.extractFeature(GradientFeatureExtractor.java:71)
        at org.openimaj.image.feature.local.detector.dog.collector.OctaveKeypointCollector.addFeature(OctaveKeypointCollector.java:87)
        at org.openimaj.image.feature.local.detector.dog.collector.OctaveKeypointCollector.foundInterestPoint(OctaveKeypointCollector.java:83)
        at org.openimaj.image.feature.local.detector.dog.pyramid.DoGOctaveExtremaFinder.foundInterestPoint(DoGOctaveExtremaFinder.java:121)
        at org.openimaj.image.feature.local.detector.pyramid.BasicOctaveExtremaFinder.processExtrema(BasicOctaveExtremaFinder.java:98)
        at org.openimaj.image.feature.local.detector.pyramid.AbstractOctaveExtremaFinder.process(AbstractOctaveExtremaFinder.java:120)
        at org.openimaj.image.feature.local.detector.pyramid.AbstractOctaveExtremaFinder.process(AbstractOctaveExtremaFinder.java:60)
        at org.openimaj.image.feature.local.detector.dog.pyramid.DoGOctaveExtremaFinder.process(DoGOctaveExtremaFinder.java:97)
        at org.openimaj.image.feature.local.detector.dog.pyramid.DoGOctaveExtremaFinder.process(DoGOctaveExtremaFinder.java:50)
        at org.openimaj.image.analysis.pyramid.gaussian.GaussianOctave.process(GaussianOctave.java:108)
        at org.openimaj.image.analysis.pyramid.gaussian.GaussianPyramid.process(GaussianPyramid.java:119)
        at org.openimaj.image.feature.local.engine.DoGSIFTEngine.findFeatures(DoGSIFTEngine.java:111)
        at AnalizadorDeImagenes.main(AnalizadorDeImagenes.java:46)
Caused by: java.lang.ClassNotFoundException: odk.lang.FastMath
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
Java Result: 1
BUILD SUCCESSFUL (total time: 5 seconds)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)

**Comment by jonhare** [comment]
Original reporter: @

**Comment by jonhare** [comment]
:  It's the same for 1.0.5


Exception in thread "main" java.lang.NoClassDefFoundError: odk/lang/FastMath
        at org.openimaj.image.processing.convolution.FImageGradients.gradientMagnitudesAndOrientations(FImageGradients.java:122)
        at org.openimaj.image.feature.local.detector.dog.extractor.OrientationHistogramExtractor.extractFeatureRaw(OrientationHistogramExtractor.java:137)
        at org.openimaj.image.feature.local.detector.dog.extractor.DominantOrientationExtractor.extractFeatureRaw(DominantOrientationExtractor.java:92)
        at org.openimaj.image.feature.local.detector.dog.extractor.GradientFeatureExtractor.extractFeature(GradientFeatureExtractor.java:96)
        at org.openimaj.image.feature.local.detector.dog.collector.OctaveKeypointCollector.addFeature(OctaveKeypointCollector.java:78)
        at org.openimaj.image.feature.local.detector.dog.collector.OctaveKeypointCollector.foundInterestPoint(OctaveKeypointCollector.java:74)
        at org.openimaj.image.feature.local.detector.dog.pyramid.DoGOctaveExtremaFinder.foundInterestPoint(DoGOctaveExtremaFinder.java:110)
        at org.openimaj.image.feature.local.detector.dog.pyramid.BasicOctaveExtremaFinder.processExtrema(BasicOctaveExtremaFinder.java:97)
        at org.openimaj.image.feature.local.detector.dog.pyramid.AbstractOctaveExtremaFinder.process(AbstractOctaveExtremaFinder.java:120)
        at org.openimaj.image.feature.local.detector.dog.pyramid.AbstractOctaveExtremaFinder.process(AbstractOctaveExtremaFinder.java:60)
        at org.openimaj.image.feature.local.detector.dog.pyramid.DoGOctaveExtremaFinder.process(DoGOctaveExtremaFinder.java:86)
        at org.openimaj.image.feature.local.detector.dog.pyramid.DoGOctaveExtremaFinder.process(DoGOctaveExtremaFinder.java:48)
        at org.openimaj.image.processing.pyramid.gaussian.GaussianOctave.process(GaussianOctave.java:108)
        at org.openimaj.image.processing.pyramid.gaussian.GaussianPyramid.process(GaussianPyramid.java:119)
        at org.openimaj.image.feature.local.engine.DoGSIFTEngine.findFeatures(DoGSIFTEngine.java:98)
        at AnalizadorDeImagenes.main(AnalizadorDeImagenes.java:45)
Caused by: java.lang.ClassNotFoundException: odk.lang.FastMath
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        ... 16 more
Java Result: 1
debug:
BUILD SUCCESSFUL (total time: 25 seconds)

Exception in thread "main" java.lang.NoClassDefFoundError: odk/lang/FastMath
        at org.openimaj.image.processing.convolution.FImageGradients.gradientMagnitudesAndOrientations(FImageGradients.java:122)
        at org.openimaj.image.feature.local.detector.dog.extractor.OrientationHistogramExtractor.extractFeatureRaw(OrientationHistogramExtractor.java:137)
        at org.openimaj.image.feature.local.detector.dog.extractor.DominantOrientationExtractor.extractFeatureRaw(DominantOrientationExtractor.java:92)
        at org.openimaj.image.feature.local.detector.dog.extractor.GradientFeatureExtractor.extractFeature(GradientFeatureExtractor.java:96)
        at org.openimaj.image.feature.local.detector.dog.collector.OctaveKeypointCollector.addFeature(OctaveKeypointCollector.java:78)
        at org.openimaj.image.feature.local.detector.dog.collector.OctaveKeypointCollector.foundInterestPoint(OctaveKeypointCollector.java:74)
        at org.openimaj.image.feature.local.detector.dog.pyramid.DoGOctaveExtremaFinder.foundInterestPoint(DoGOctaveExtremaFinder.java:110)
        at org.openimaj.image.feature.local.detector.dog.pyramid.BasicOctaveExtremaFinder.processExtrema(BasicOctaveExtremaFinder.java:97)
        at org.openimaj.image.feature.local.detector.dog.pyramid.AbstractOctaveExtremaFinder.process(AbstractOctaveExtremaFinder.java:120)
        at org.openimaj.image.feature.local.detector.dog.pyramid.AbstractOctaveExtremaFinder.process(AbstractOctaveExtremaFinder.java:60)
        at org.openimaj.image.feature.local.detector.dog.pyramid.DoGOctaveExtremaFinder.process(DoGOctaveExtremaFinder.java:86)
        at org.openimaj.image.feature.local.detector.dog.pyramid.DoGOctaveExtremaFinder.process(DoGOctaveExtremaFinder.java:48)
        at org.openimaj.image.processing.pyramid.gaussian.GaussianOctave.process(GaussianOctave.java:108)
        at org.openimaj.image.processing.pyramid.gaussian.GaussianPyramid.process(GaussianPyramid.java:119)
        at org.openimaj.image.feature.local.engine.DoGSIFTEngine.findFeatures(DoGSIFTEngine.java:98)
        at AnalizadorDeImagenes.main(AnalizadorDeImagenes.java:45)
Caused by: java.lang.ClassNotFoundException: odk.lang.FastMath
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        ... 16 more
Java Result: 1
debug:
BUILD SUCCESSFUL (total time: 25 seconds)

**Comment by jonhare** [comment]
:  There is a missing jar file. (JAFAMA-jar)

**Comment by jonhare** [comment]
:  Another jar file: trove-3.0.3 

Exception in thread "main" java.lang.NoClassDefFoundError: gnu/trove/list/array/TFloatArrayList

Another jar file: bezier-utils.jar 

Exception in thread "main" java.lang.NoClassDefFoundError: com/caffeineowl/graphics/bezier/CubicSegmentConsumer

I added and it run OK.

**Comment by congqiyuan** [comment]
the same problem happens to the Imageterrier project.
Could you please tell me how to add the missing jar files?

**Comment by RobinTalkwalker** [comment]
This issue is still happening
