### ISSUE TITLE
Colt jar does not contain jal/objects/BinaryPredicate

### ISSUE THREAD

**Issue by MrFirekiller** [openimaj/openimaj#346]
The colt jar does not have 
```java
jal/objects/BinaryPredicate
```
as opposed to the original colt jar. This results in the exception:
```java
Exception in thread "main" java.lang.NoClassDefFoundError: jal/objects/BinaryPredicate
	at org.openimaj.knn.approximate.ByteNearestNeighboursKDTree.<init>(ByteNearestNeighboursKDTree.java:124)
	at org.openimaj.feature.local.matcher.FastBasicKeypointMatcher.setModelFeatures(FastBasicKeypointMatcher.java:134)
	at org.openimaj.feature.local.matcher.consistent.ConsistentLocalFeatureMatcher2d.setModelFeatures(ConsistentLocalFeatureMatcher2d.java:156)
	at Inveniemini.ImageProcessor.main(ImageProcessor.java:73)
Caused by: java.lang.ClassNotFoundException: jal.objects.BinaryPredicate
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 4 more
```
Introducing the real jar or a version of it in various ways just confuses the program and throws this:
```java
Exception in thread "main" java.lang.NoClassDefFoundError: jal/Object/BinaryPredicate (wrong name: jal/objects/BinaryPredicate)
```
which contrasts with the first error message. I am using gradle as my build tool. How can I solve this?
Thank you.

**Comment by jonhare** [comment]
the colt jar isn't supposed to have jal.objects.BinaryPredicate - that's in the jal jar (http://maven.ecs.soton.ac.uk/content/groups/maven.openimaj.org/vigna/dsi/unimi/it/jal/20031117/)

**Comment by MrFirekiller** [comment]
Thank you for the response.
Unfortunately it isn't there.
![image](https://user-images.githubusercontent.com/91788203/152604938-fecb2cba-fa64-40bd-8e2f-841fc3efa1cb.png)

**Comment by jonhare** [comment]
okay, that's interesting. What do you have in your gradle file?

**Comment by MrFirekiller** [comment]
```groovy
plugins {
    id 'java-library'
}

repositories {
	mavenCentral()
}

dependencies {
    api 'com.amazon.alexa:ask-sdk:2.42.1'
    compile 'com.github.sarxos:webcam-capture:0.3.12'
    compile 'org.openimaj:faces:1.3.10'
    compile 'mysql:mysql-connector-java:6.0.6'
    implementation files('lib/jal-20031117.jar')
	implementation group: 'log4j', name: 'log4j', version: '1.2.17'
}
```

**Comment by jonhare** [comment]
try changing the repositories bit of the gradle to this:

repositories {
    mavenCentral()
    maven {
        url "https://maven.openimaj.org"
    }
}
and doing a clean rebuild... Does that fix it?

**Comment by Manthan-T** [comment]
jal-20031117.jar is now there if I do that. Before that I also tried using the link you sent before and put the jar into the build.gradle and that works too. It succeeded in doing the match that required the BinaryPredicate. Thank you for your help.
