### ISSUE TITLE
Not able to use VideoCapture on Raspberry Pi

### ISSUE THREAD

**Issue by jonhare** [openimaj/openimaj#47]
OP-48: After last change regarding OP-41, *.so object available in official repo for ARM 32 (including Raspberry Pi) is invalid.

Problem reported in [webcam-capture issue #27|https://github.com/sarxos/webcam-capture/issues/27] project by [t-oster|https://github.com/t-oster].

System:

{code}
/proc/cpuinfo:
Processor   : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS    : 464.48
Features    : swp half thumb fastmult vfp edsp java tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant : 0x0
CPU part    : 0xb76
CPU revision    : 7

Hardware    : BCM2708
Revision    : 0002
Serial      : 0000000045873531

uname -a
Linux alarmpi 3.6.11-3-ARCH+ #1 PREEMPT Thu Jan 10 03:05:04 UTC 2013 armv6l GNU/
{code}

Stacktrace:

{code}
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so : /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so: undefined symbol: v4lconvert_enum_frameintervals
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so : /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so: undefined symbol: v4lconvert_enum_frameintervals
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so : /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so: undefined symbol: v4lconvert_enum_frameintervals
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so : /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so: undefined symbol: v4lconvert_enum_frameintervals
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so : /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so: undefined symbol: v4lconvert_enum_frameintervals
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so : /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so: undefined symbol: v4lconvert_enum_frameintervals
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so : /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so: undefined symbol: v4lconvert_enum_frameintervals
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so : /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so: undefined symbol: v4lconvert_enum_frameintervals
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so : /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so: undefined symbol: v4lconvert_enum_frameintervals
# BridJ: dlopen error when loading /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so : /tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so: undefined symbol: v4lconvert_enum_frameintervals
java.lang.RuntimeException: Library 'OpenIMAJGrabber' was not loaded successfully from file '/tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so'
    at org.bridj.BridJ.getNativeLibrary(BridJ.java:922)
    at org.bridj.BridJ.getNativeLibrary(BridJ.java:901)
    at org.bridj.BridJ.getNativeLibrary(BridJ.java:513)
    at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:627)
    at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:828)
    at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:755)
    at org.bridj.CRuntime$CTypeInfo.initialize(CRuntime.java:209)
    at org.bridj.BridJ.initialize(BridJ.java:970)
    at org.bridj.NativeObject.<init>(NativeObject.java:23)
    at org.bridj.StructObject.<init>(StructObject.java:14)
    at org.bridj.cpp.CPPObject.<init>(CPPObject.java:27)
    at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.<init>(OpenIMAJGrabber.java:64)
    at com.github.sarxos.webcam.ds.buildin.WebcamGrabberProcessor$NewGrabberTask.handle(WebcamGrabberProcessor.java:81)
    at com.github.sarxos.webcam.ds.buildin.WebcamGrabberProcessor$StaticProcessor.run(WebcamGrabberProcessor.java:52)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)
Exception in thread "ProcessorThreadFactory" java.lang.RuntimeException: Failed to allocate new instance of type class com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber
    at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:674)
    at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:828)
    at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:755)
    at org.bridj.CRuntime$CTypeInfo.initialize(CRuntime.java:209)
    at org.bridj.BridJ.initialize(BridJ.java:970)
    at org.bridj.NativeObject.<init>(NativeObject.java:23)
    at org.bridj.StructObject.<init>(StructObject.java:14)
    at org.bridj.cpp.CPPObject.<init>(CPPObject.java:27)
    at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.<init>(OpenIMAJGrabber.java:64)
    at com.github.sarxos.webcam.ds.buildin.WebcamGrabberProcessor$NewGrabberTask.handle(WebcamGrabberProcessor.java:81)
    at com.github.sarxos.webcam.ds.buildin.WebcamGrabberProcessor$StaticProcessor.run(WebcamGrabberProcessor.java:52)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)
Caused by: java.lang.RuntimeException: Library 'OpenIMAJGrabber' was not loaded successfully from file '/tmp/BridJExtractedLibraries3429022544279638110/OpenIMAJGrabber.so'
    at org.bridj.BridJ.getNativeLibrary(BridJ.java:922)
    at org.bridj.BridJ.getNativeLibrary(BridJ.java:901)
    at org.bridj.BridJ.getNativeLibrary(BridJ.java:513)
    at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:627)
    ... 13 more
{code}

After *.so investigation I discovered that OpenIMajGrabber.so from [r1710|http://sourceforge.net/p/openimaj/code/1710/] is much smaller comparing it to the previous one from [r975|http://sourceforge.net/p/openimaj/code/975/] which is probably caused by the fact that some symbols in [r1710|http://sourceforge.net/p/openimaj/code/1710/] are undefined which cause BridJ to fail OpenIMAJGrabber.so loading

Example:

[r1710|http://sourceforge.net/p/openimaj/code/1710/]:

{code}
$ nm -Ca OpenIMAJGrabber.so | grep -i frameintervals
         U v4lconvert_enum_frameintervals
{code}

[r975|http://sourceforge.net/p/openimaj/code/975/]:

{code}
$ nm -Ca OpenIMAJGrabber.so | grep -i frameintervals
0000ba0c T v4lconvert_enum_frameintervals
{code}

Temporary W/A is to replace new binary by the old one and recompile.

**Comment by jonhare** [comment]
Original reporter: @sarxos

**Comment by jonhare** [comment]
jonhare:  hmm, that's interesting... you were able to get the old one working? We were trying this yesterday and ended up having to recompile the openimaj grabber library & also use a different version of the bridj library. What OS are you using on the pi? is it the hardFP or softFP variant? and what JVM? (we were trying rasbian hardfp with the oracle java 8 preview)

**Comment by jonhare** [comment]
sarxos:  Jonathon, this issue has been initially reported by Thomas Oster in [webcam-capture issue #27|https://github.com/sarxos/webcam-capture/issues/27] and I don't know the environement details. He was trying to use my webcam-capture library which uses OpenIMAJGrabber (it's really nice!) and found this bug. I replaced newest *.so with the old one as w/a. Thomas confirmed that my code is working fine with this change. I'm using BridJ 0.6.2. Feel free to comment on [webcam-capture issue #27|https://github.com/sarxos/webcam-capture/issues/27] to ask Thomas for any additional details since I don't know anything more except what I included in the issue description. Sorry for that :(

**Comment by jonhare** [comment]
hepin1989:  OK,here i am,I reported the issue [#28](https://github.com/sarxos/webcam-capture/issues/28)

I was trying to use the webcam-capture library on raspberry pi with model B,runs the [Raspbian “wheezy”](http://www.raspberrypi.org/downloads),and as i have noticed before ,as the quote below:
>Soft-float Debian “wheezy”
>This image is identical to the Raspbian “wheezy” image, but uses the slower soft-float ABI. It is only intended for use with software such as >the Oracle JVM which does not yet support the hard-float ABI used by Raspbian.
I use the first one instead the second one cause i don't need to upgrade my linux framework and can unlock my hole 512M RAM,sorry for the lazy.
I use it to run some java code with OK,until i finally come to the #28 issue.

My environement is OK,i use the  ppa:webupd8team/java,and it's the last version of oracle java 7.
Linux:Raspbian “wheezy”, hard float ABI (this cause the problem)

when i run the test code,it always crash and report no such file blablabla....,and after  Bartosz Firyn  report this to the bridj at [#364](https://github.com/ochafik/nativelibs4java/issues/364), I tryed the bridj 6.2.3 snapshot jar,then the bridj load is ok,but issue comes to can't load OpenIMAJGrabber.so.

I followed to the Bartosz Firyn's advice ,add this OpenIMAJGrabber.so to the /usr/lib ,and it crash too,and report :no such file or directory.

lately,an guys come to show that the cause is the Hard-float and Soft-Float,and the Arch-Linux is both OK,you can see here [#364](https://github.com/ochafik/nativelibs4java/issues/364)

after i change to the slower one,Soft-float Debian “wheezy”,the code works as i expected.

thanks your guys hard work

**Comment by jonhare** [comment]
jonhare:  Current SNAPSHOT is now working on ARMEL and ARMHF raspbian.

**Comment by jonhare** [comment]
sarxos:  Thank you Jonathon! You are great :D

**Comment by jonhare** [comment]
hepin1989:  Thanks a lot ,I make the OpenIMAJGrabber.so and then copy it to $Home,it works for me.thanks Jonathon and Bartosz Firyn
