### ISSUE TITLE
It's impossible to perform searches containing one or more features having hash values not any of the LSH tables

### ISSUE THREAD

**Issue by jonhare** [openimaj/openimaj#57]
OP-58: The exactNN method will throw an exception if the {{subset}} parameter is empty. This happens when the hash code of a query feature, is not found in any of the hash tables. This causes the whole search to fail.

The following is a stack trace using revision #1946.
{code}
java.lang.IllegalArgumentException
	at java.util.PriorityQueue.<init>(PriorityQueue.java:135)
	at org.openimaj.util.queue.InvertedPriorityQueue.<init>(InvertedPriorityQueue.java:80)
	at org.openimaj.util.queue.BoundedPriorityQueue.<init>(BoundedPriorityQueue.java:81)
	at org.openimaj.knn.lsh.LSHNearestNeighbours.exactNN(LSHNearestNeighbours.java:362)
	at org.openimaj.knn.lsh.LSHNearestNeighbours.searchKNN(LSHNearestNeighbours.java:322)
{code}

**Comment by jonhare** [comment]
Original reporter: @pcmoen

**Comment by jonhare** [comment]
jonhare:  Good catch; what should happen when it isn't possible to determine a nearest neighbour (or k-th NN) isn't deal't with in the javadoc either. 

I've made the executive decision that if a KNN implementation can't find a neighbour it will return an index of -1 for the methods that take result arrays as parameters, null for the searchNN method, and a list of potentially less than K items for the searchKNN method. This is documented in the javadoc of the NearestNeighbours interface in commit #1950. 

Commit #1950 should also fix the reported problem and make the LSHNearestNeighbours behave as described in the new javadoc additions when a query fails to collide.

**Comment by jonhare** [comment]
pcmoen:  Start of unit test for the LSHNearestNeighbours implementation.

**Comment by jonhare** [comment]
jonhare:  Fantastic - thanks!

**Comment by jonhare** [comment]
jonhare:  Documented and integrated initial unit tests from the attachment in #1952
