### ISSUE TITLE
Compile OpenIMAJGrabber.dll so both msvcp100.dll, msvcr100.dll are included

### ISSUE THREAD

**Issue by jonhare** [openimaj/openimaj#58]
OP-59: Hi,

On some systems Java fails to load OpenIMAJGrabber.dll:

{code}
java.lang.RuntimeException: Library 'OpenIMAJGrabber' was not loaded successfully from file 'C:\Users\USER\AppData\Local\Temp\BridJExtractedLibraries7239214121169806436\OpenIMAJGrabber.dll' 
at org.bridj.BridJ.getNativeLibrary(BridJ.java:952) 
at org.bridj.BridJ.getNativeLibrary(BridJ.java:931) 
... etc
{code}

It's caused by missing msvcp100.dll and msvcr100.dll files which are part of Microsoft Visual C++ 2010 Redistributable Package.

So my question is - is it possible to compile OpenIMAJGrabber.dll in such a way that both those DLLs are included? I found *[this|http://msdn.microsoft.com/en-us/library/2kzt1wy3.aspx]* article where */MT* option is described, which, according to *[this|http://stackoverflow.com/questions/7487710/build-c-project-to-include-all-msvc-dlls]* stackoverflow question should resolve this problem by static linking.

Thank you!

**Comment by jonhare** [comment]
Original reporter: @sarxos

**Comment by jonhare** [comment]
jonhare:  I've just recompiled the libs using /MT rather than /MD. The new versions are ~100K larger, so it looks like there is extra statically linked code in there. 
The new dlls have been committed in #1976. I checked that it still runs (on a VM with the dlls present); I haven't got a machine without the dlls to test on though...

**Comment by jonhare** [comment]
sarxos:  Thank you Jon!

I will try to setup VM with clean system without the Visual C++ Redistributable package installed to check if it's working without the DLLs or I will simply remove these DLLs from my second system and check what is the effect.

I suppose we will know the answer soon after I update the binaries in the refined OpenIMAJ driver I'm using by default in the Webcam Capture code. There were few users who reported exactly the same problem, so we can probably assume it's fixed when there will be no more reports regarding this problem ;]

Will let you know asap!

**Comment by jonhare** [comment]
sarxos:  Jon,

I confirmed the fix on my 32-bit Windows XP running on Virtual Box, but still [waiting|https://github.com/sarxos/webcam-capture/issues/81] for the feedback from the Webcam Capture users who are affected by this problem.

Thank you very much for fixing this, we really appreciate your help :D

**Comment by jonhare** [comment]
jonhare:  Closing as fixed. Reopen if it's still an issue.
