### ISSUE TITLE
Compile libOpenIMAJGrabber for MacOS 10.5

### ISSUE THREAD

**Issue by jonhare** [openimaj/openimaj#61]
OP-62: Hi,

Recently one of the users have open a ticket against webcam-capture with description showing that OpenIMAJGrabber cannot be loaded:

{code}
Caused by: java.lang.RuntimeException: Library 'OpenIMAJGrabber' was not loaded successfully from file '/var/folders/V9/V9vTbgg9HP0MIVC2NNXMdE+++TM/-Tmp-/BridJExtractedLibraries260162122153549525/libOpenIMAJGrabber.dylib'
    at org.bridj.BridJ.getNativeLibrary(BridJ.java:952)
    at org.bridj.BridJ.getNativeLibrary(BridJ.java:931)
    at org.bridj.BridJ.getNativeLibrary(BridJ.java:543)
    at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:652)
    ... 13 more
{code}

That was because of:

{code}
# BridJ: dlopen error when loading /var/folders/V9/V9vTbgg9HP0MIVC2NNXMdE+++TM/-Tmp-/BridJExtractedLibraries260162122153549525/libOpenIMAJGrabber.dylib : dlopen(/var/folders/V9/V9vTbgg9HP0MIVC2NNXMdE+++TM/-Tmp-/BridJExtractedLibraries260162122153549525/libOpenIMAJGrabber.dylib, 1): no suitable image found.  Did find:
    /var/folders/V9/V9vTbgg9HP0MIVC2NNXMdE+++TM/-Tmp-/BridJExtractedLibraries260162122153549525/libOpenIMAJGrabber.dylib: unknown required load command 0x80000022
{code}

I googled a little bit and found that _unknown required load command 0x80000022_ means that OSX does not understand LC_DYLD_INFO_ONLY load command which has been introduced in OSX 10.6. Therefore users who are working with 10.5 are not able to use it. 

It seems it's possible to compile libOpenIMAJGrabber.dylib and have backward compatibility with 10.5 - from what I found in github, it's enough to add:

{code}
MACOSX_DEPLOYMENT_TARGET = 10.6
{code}

In the **.xcconfig* file for the specific project.

Thank you guys! Your project rocks!

**Comment by jonhare** [comment]
Original reporter: @sarxos

**Comment by jonhare** [comment]
sarxos:  It should be:

{code}
MACOSX_DEPLOYMENT_TARGET = 10.5
{code}

My mistake, sorry ;P

**Comment by jonhare** [comment]
jonhare:  Should be fixed in svn commit #2073, but I haven't got any way to test it (other than checking it still works on OSX 10.8). Re-open this ticket if it is still a problem.

**Comment by jonhare** [comment]
sarxos:  Thank you Jonathon!

I will pass the newest binary to the user who initially found this problem and ask him to confirm if this fix the issue he mentioned.

**Comment by jonhare** [comment]
sarxos:  Just FYI, user reported that everything works fine :) Thank you Jon!

**Comment by jonhare** [comment]
jonhare:  Fantastic. Many thanks.
