### ISSUE TITLE
VideoShotDetector(s) crash on longer videos

### ISSUE THREAD

**Issue by jonhare** [openimaj/openimaj#63]
OP-64: Hi,

I'm trying to execute the video boundary detection demos. I tried the HistogramVideoShotDetector and the LocalVideoShotDetector, however they both crash at longer videos. My machines has 16 gigs of RAM and the JVM gets most of it. After a couple of shots, depending on the algorithm, I get a "java.lang.OutOfMemoryError". I tried to fix it myself, even went so far as to define my own VideoShotDetector, but I guess the problem lies deeper in the framework. I'd be really happy if someone that knows the codebase better could give me a tip on how to fix it, or could look into it.
The error message I get, running the VideoShotDetectorVisualisation.java on a 40 minute video is: 

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.openimaj.image.FImage.<init>(FImage.java:121)
	at org.openimaj.image.FImage.clone(FImage.java:388)
	at org.openimaj.image.FImage.clone(FImage.java:58)
	at org.openimaj.image.MultiBandImage.clone(MultiBandImage.java:341)
	at org.openimaj.image.MultiBandImage.clone(MultiBandImage.java:52)
	at org.openimaj.video.processing.shotdetector.VideoKeyframe.clone(VideoKeyframe.java:93)
	at org.openimaj.video.processing.shotdetector.VideoShotDetector.checkForShotBoundary(VideoShotDetector.java:310)
	at org.openimaj.video.processing.shotdetector.VideoShotDetector.processFrame(VideoShotDetector.java:436)
	at org.openimaj.video.processor.VideoProcessor.process(VideoProcessor.java:131)
	at org.openimaj.video.processing.shotdetector.VideoShotDetector.process(VideoShotDetector.java:184)
	at org.openimaj.demos.video.VideoShotDetectorVisualisation.main(VideoShotDetectorVisualisation.java:177)
16:27:04.786 [Finalizer] DEBUG com.xuggle.xuggler - Closing dangling Container (../../../../../../../csrc/com/xuggle/xuggler/Container.cpp:146)
16:27:04.789 [Finalizer] DEBUG com.xuggle.xuggler - Closing dangling StreamCoder (../../../../../../../csrc/com/xuggle/xuggler/StreamCoder.cpp:96)
16:27:04.789 [Finalizer] DEBUG com.xuggle.xuggler - Closing dangling StreamCoder (../../../../../../../csrc/com/xuggle/xuggler/StreamCoder.cpp:96)

**Comment by jonhare** [comment]
Original reporter: @

**Comment by jonhare** [comment]
jonhare:  Dave - can you take a look?

**Comment by jonhare** [comment]
davedupplaw:  The VideoShotDetector stores all the keyframes it finds in a list in memory (by default). That might become a pretty big memory hog on a large video.  You can turn that off with VideoShotDetector#setFindKeyFrames(boolean).  It will then only store the position in the video at which the shot boundary was detected and not the frame itself.  If you want to store the frames somewhere, you can add a ShotDetectedListener using VideoShotDetector#addShotDetectedListener(ShotDetectedListener) that is called each time a new shot boundary is found during processing.  The VideoKeyFrame that's passed in the event will not have the frame in it if findKeyFrames is false. So you will need to use Video#getCurrentFrame() to get the current frame. That's the workaround for now. I will probably rearrange the VideoShotDetector code so that it will pass the keyframe in that event but won't store it if findKeyFrames is false.

**Comment by jonhare** [comment]
jonhare:  Closing as I think this is resolved. Reopen if there is still a problem.
