### ISSUE TITLE
Problem with the 3D visualisations in Mac

### ISSUE THREAD

**Issue by jonhare** [openimaj/openimaj#64]
OP-65: When you try to run anything which uses jogl you get a messed up looking window and this error:

Exception in thread "main-Display-.macosx_nil-1-EDT-1" javax.media.opengl.GLException: Not a GL2 implementation
	at jogamp.opengl.gl4.GL4bcImpl.getGL2(GL4bcImpl.java:34641)
	at org.openimaj.vis.Visualisation3D.init(Visualisation3D.java:118)
	at org.openimaj.vis.general.HeightMap3D.init(HeightMap3D.java:254)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:332)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:371)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:358)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:280)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:655)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:594)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:543)
	at jogamp.opengl.GLAutoDrawableBase.defaultWindowRepaintOp(GLAutoDrawableBase.java:99)
	at com.jogamp.newt.opengl.GLWindow.access$000(GLWindow.java:94)
	at com.jogamp.newt.opengl.GLWindow$1.windowRepaint(GLWindow.java:107)
	at jogamp.newt.WindowImpl.consumeWindowEvent(WindowImpl.java:2392)
	at jogamp.newt.WindowImpl.consumeEvent(WindowImpl.java:1943)
	at jogamp.newt.DisplayImpl.dispatchMessage(DisplayImpl.java:388)
	at jogamp.newt.DisplayImpl.dispatchMessages(DisplayImpl.java:436)
	at jogamp.newt.DisplayImpl$DispatchMessagesRunnable.run(DisplayImpl.java:371)
	at jogamp.newt.DefaultEDTUtil$EventDispatchThread.run(DefaultEDTUtil.java:293)
Exception in thread "main-AWTAnimator-1" javax.media.opengl.GLException: Not a GL2 implementation
	at jogamp.opengl.gl4.GL4bcImpl.getGL2(GL4bcImpl.java:34641)
	at org.openimaj.vis.Visualisation3D.display(Visualisation3D.java:152)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:373)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:358)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:280)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:655)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:594)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:543)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:74)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:142)
	at com.jogamp.opengl.util.Animator$MainLoop.run(Animator.java:176)
	at java.lang.Thread.run(Thread.java:724)

Little to no mention of this anywhere online.

**Comment by jonhare** [comment]
Original reporter: @sinjax

**Comment by jonhare** [comment]
davedupplaw:  Changed the canvas to be GL2 not GL3 as all render functionality uses GL2.
