### ISSUE TITLE
OpenIMAJGrabber can not get webcam device 

### ISSUE THREAD

**Issue by jonhare** [openimaj/openimaj#70]
OP-71: OpenIMAJGrabber can not get device, always return 0.
    	DeviceList devices = new DeviceList();
    	int nd = devices.getNumDevices();

If using: video = new VideoCapture(320, 240); gets this error:

INFO: Not enough args for null OpenIMAJGrabber.startSession(int, int, double)
Exception in thread "Thread-2" java.lang.RuntimeException: org.openimaj.video.capture.VideoCaptureException: Timed out waiting for next frame

**Comment by jonhare** [comment]
Original reporter: @

**Comment by jonhare** [comment]
:  
My false, it is working at least on getting devices. I checkout native code and working well in Maverick. The Java code, after I set System.setProperty(DEFAULT_DEVICE_NUMBER_PROPERTY, "0"); the device returns properly. However, this code:
	System.setProperty(DEFAULT_DEVICE_NUMBER_PROPERTY, "0");
        video = new VideoCapture(320, 240);
        display = VideoDisplay.createVideoDisplay(video);
        SwingUtilities.getRoot(display.getScreen()).addKeyListener(this);

still has these exception:

Apr 28, 2014 1:18:24 PM org.bridj.BridJ log
INFO: Not enough args for null OpenIMAJGrabber.startSession(int, int, double)
Exception in thread "Thread-2" java.lang.RuntimeException: org.openimaj.video.capture.VideoCaptureException: Timed out waiting for next frame
	at org.openimaj.video.capture.VideoCapture.getNextFrame(VideoCapture.java:288)
	at org.openimaj.video.capture.VideoCapture.getNextFrame(VideoCapture.java:70)
	at org.openimaj.video.VideoDisplay.run(VideoDisplay.java:503)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openimaj.video.capture.VideoCaptureException: Timed out waiting for next frame
	... 4 more

**Comment by jonhare** [comment]
:  The problem maybe because:

I am using Eclipse which has option to automatically add -XstartOnFirstThread on running program if the classpath includes "SWT" jar(even the project never use it). 

Actually, I used webcam capture Java project which refers your native code. After I turn off this option, webcam capture working... I don't do further test on your code but assume same.

**Comment by jonhare** [comment]
jonhare:  Closing because this is not an issue if -XstartOnFirstThread is not used. Please open a new issue if SWT support is needed.
