### ISSUE TITLE
JAVAFX core-video-capture exception

### ISSUE THREAD

**Issue by jonhare** [openimaj/openimaj#71]
OP-72: I created a JavaFX application using the library:

core-video-capture-1.3-SNAPSHOT.jar

If I run the application using java:

java -jar myjarfile.jar

Its works perfectly.

But, If I run the application using WinLauncher.exe (JavaFX packaging) I have an exception.
The program has unexpectedly finished

I actived the Bridj using:

set BRIDJ_VERY_VERBOSE=1 

and I see this exception:

[JavaFX Application Thread] DEBUG SYSERR  - java.lang.ExceptionInInitializerError
[JavaFX Application Thread] DEBUG SYSERR  - 	at org.bridj.CallbackNativeImplementer.getDynamicCallback(CallbackNativeImplementer.java:98)
[JavaFX Application Thread] DEBUG SYSERR  - 	at org.bridj.CRuntime.getDynamicFunctionFactory(CRuntime.java:530)
[JavaFX Application Thread] DEBUG SYSERR  - 	at org.bridj.cpp.CPPRuntime.getConstructor(CPPRuntime.java:568)
[JavaFX Application Thread] DEBUG SYSERR  - 	at org.bridj.cpp.CPPRuntime.newCPPInstance(CPPRuntime.java:636)
[JavaFX Application Thread] DEBUG SYSERR  - 	at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:833)
[JavaFX Application Thread] DEBUG SYSERR  - 	at org.bridj.cpp.CPPRuntime$CPPTypeInfo.initialize(CPPRuntime.java:1)
[JavaFX Application Thread] DEBUG SYSERR  - 	at org.bridj.CRuntime$CTypeInfo.initialize(CRuntime.java:219)
[JavaFX Application Thread] DEBUG SYSERR  - 	at org.bridj.BridJ.initialize(BridJ.java:969)
[JavaFX Application Thread] DEBUG SYSERR  - 	at org.bridj.NativeObject.<init>(NativeObject.java:23)
[JavaFX Application Thread] DEBUG SYSERR  - 	at org.bridj.StructObject.<init>(StructObject.java:14)
[JavaFX Application Thread] DEBUG SYSERR  - 	at org.bridj.cpp.CPPObject.<init>(CPPObject.java:27)
[JavaFX Application Thread] DEBUG SYSERR  - 	at org.openimaj.video.capture.OpenIMAJGrabber.<init>(OpenIMAJGrabber.java:58)
[JavaFX Application Thread] DEBUG SYSERR  - 	at org.openimaj.video.capture.VideoCapture.getVideoDevices(VideoCapture.java:220)
[JavaFX Application Thread] DEBUG SYSERR  - 	at com.novovia.camaralib.NovoviaCamaraOIM.NovoviaCamara(NovoviaCamaraOIM.java:116)

....

I see the path of library is set up perfectly.

[JavaFX Application Thread] DEBUG SYSERR  - may 20, 2014 4:10:07 PM org.bridj.BridJ log
Información: Property java.library.path = C:\Desarrollos\NovoviaSistema\sandbox\app\;C:\Program Files\ImageMagick-6.8.8-Q16;C:\jet8.0-eval-amd64\bin;C:\Program Files (x86)\PC Connectivity Solution\;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\;C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\x64\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Mercurial\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\TortoiseHg\;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\nodejs\;C:\Git\cmd;C:\Program Files (x86)\Tesseract-OCR;C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\;C:\Program Files\Calibre2\;C:\Program Files\Microsoft Network Monitor 3\;c:\users\bnb\appdata\local\enthought\canopy32\user\scripts;C:\Program Files (x86)\CMake 2.8;C:\Program Files\Java\jdk1.7.0_45\bin;C:\AppServ\Apache2.2\bin;C:\AppServ\php5;C:\AppServ\MySQL\bin;C:\apache-maven-3.0.5\bin;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\openCV;C:\Desarrollos\gradle-1.8\bin;C:\Program Files (x86)\Inno Setup 5;C:\cygwin64\bin;C:\Desarrollos\apache-ant-1.9.2\bin;;C:\Windows;C:\Windows\System32;C:\Program Files\Oracle\VirtualBox;C:\Desarrollos\JAVAFX_Android\adt-bundle-windows-x86_64-20131030\sdk\tools;C:\Users\BNB\AppData\Roaming\npm;C:\Python27;C:\Program Files (x86)\Tesseract-OCR;C:\Users\BNB\AppData\Local\Enthought\Canopy32\User;C:\Users\BNB\AppData\Local\Enthought\Canopy32\User\Scripts;C:\Windows;C:\Windows\System32;C:\Windows\Microsoft.NET\Framework\v4.0.30319;

Do I need to load another library?

Thanks

Javier

**Comment by jonhare** [comment]
Original reporter: @

**Comment by jonhare** [comment]
:  I did the same on Ubuntu 12.04. 

I'm receiving the same error.


(Please see ubuntu1204.log)

**Comment by jonhare** [comment]
jonhare:  I'm trying to replicate this on OSX and in a ubuntu 12.04 VM, but haven't had any luck as of yet. The actual "cause" of the error seems to a a NPE on line 46 of org.bridj.util.JNIUtils, which is the following:

private static final String bridjPackage = BridJ.class.getPackage().getName();

This indicates that for some reason under your javafx packaged apps the getPackage() method on the Bridj class is returning null. The only reason I can think of that could cause this is if the JavaFX packaging uses a different class loader... 

To investigate further I need to be able to reproduce the issue. Can you tell me what version of java you're using and how you create the (ubuntu) packaged application?

**Comment by jonhare** [comment]
:  Yes, JAVAFX uses its own class loader. It can explain why the error.

................


            ClassLoader sysldr = ClassLoader.getSystemClassLoader();
            
            ClassLoader urlClassLoader = new NURLClassLoader(urls, sysldr);
            
            Class launchClass = Class.forName(fxLaunchClassName, true,
                    urlClassLoader);
            Method m = launchClass.getMethod("launchApplication", argTypes);
            if (m != null) {
                Thread.currentThread().setContextClassLoader(urlClassLoader);
                return m;
            }
        } catch (Exception ex) {
            if (jfxRtPath != null) {
                ex.printStackTrace();
            }
        }

        return null;
...................


I have access to the code of the launcher. Can we add something to include the bridge package?

I will prepare a simple application to reproduce the issue and I will send you.

I'm using JDK 1.7u55 with Netbeans 7.4. I will try to create a virtual box machine. I don't know the size.

**Comment by jonhare** [comment]
:  I found the difference.

The standard JAVAFX works perfectly.

We are working over JAVAFX code and I'm trying to do a change in the java application launcher.

We replaced the class loader.

The standard to search for a main classe uses:

{code:title=Standard Class Loader|borderStyle=solid}
ClassLoader urlClassLoader = new URLClassLoader(urls, null);
Class launchClass = Class.forName(fxLaunchClassName, true,urlClassLoader);
Method m = launchClass.getMethod("launchApplication", argTypes);
{code} 

I created a new class loader: 

{code:title=New Class Loader|borderStyle=solid}
ClassLoader sysldr = ClassLoader.getSystemClassLoader();
ClassLoader urlClassLoader = new NURLClassLoader(urls, sysldr);
Class launchClass = Class.forName(fxLaunchClassName, true,urlClassLoader);
Method m = launchClass.getMethod("launchApplication", argTypes);*
{code} 

I'm trying to understand how it impact to JBRID.

**Comment by jonhare** [comment]
:  Hi Jon:

Thanks to your information, BRIDJ been able to resolve the incident.

We need to use the last BRIDJ (bridj-0.7-20140529.001545-63.jar)

Here you have the detail.

https://github.com/ochafik/nativelibs4java/issues/505

Now I will test over Ubuntu.

**Comment by jonhare** [comment]
jonhare:  Let me know if Olivier's change to Bridj fixes all the issues... I'll update the bridj version we're using shortly so that we have that fix by default.

**Comment by jonhare** [comment]
jonhare:  I've just committed (#2520) to use bridj 0.6.3-20140603 (from my github fork - I've got some linux/arm improvements that other OpenIMAJ users asked for a while ago, that haven't yet been folded back into Olivier's master). 0.6.3-20140603 incorporates the fix Olivier made to 0.7-SNAPSHOT, so *should* fix the original problem. Let me know if you're able to test it & whether it works.

**Comment by jonhare** [comment]
:  Hi, I will do the test this weekend. Thanks!!
