### ISSUE TITLE
LiblinearAnnotator mode MULTILABEL crashes on multiple classes with any solver except for logistic regression

### ISSUE THREAD

**Issue by jonhare** [openimaj/openimaj#77]
OP-78: Training goes well but predicting throws an ArrayIndexOutOfBounds exception.

at org.openimaj.ml.annotation.linear.LiblinearAnnotator$InternalModel.computeProbabilities(LiblinearAnnotator.java:151)
at org.openimaj.ml.annotation.linear.LiblinearAnnotator$Multilabel.annotate(LiblinearAnnotator.java:433)
at org.openimaj.ml.annotation.linear.LiblinearAnnotator.annotate(LiblinearAnnotator.java:522)
at org.openimaj.ml.annotation.AbstractAnnotator.classify(AbstractAnnotator.java:59)
...

My assumption is that the problem lies in computing the number of classes from annotationsList in computeProbabilities(prob_estimates):

143 final int nr_class = annotationsList.size();

Because, the given prob_estimates is of length 2 (for MULTILABEL and not using logistic regression):

410 final double[] prob_estimates = new double[2];
411 clz = DenseLinear.predictValues(models[i], feature, prob_estimates);
412 computeProbabilities(prob_estimates);

And annotationList is the length of the number of actual classes.

342 annotationsList = new ArrayList<ANNOTATION>(annotations);

It will then attempt to assign an array index that is out of bounds in prob_estimates. (prob_estimates[2] causes the program to crash).

**Comment by jonhare** [comment]
Original reporter: @vla_ve

**Comment by jonhare** [comment]
jonhare:  Should be fixed in commit #2627 (1.4-SNAPSHOT)
