### ISSUE TITLE
SandeepFaceDetector throws NullPointerException

### ISSUE THREAD

**Issue by bisoldi** [openimaj/openimaj#88]
I get the following NullPointerException when processing an MBFImage through SandeepFaceDetector.

Exception in thread "main" java.lang.NullPointerException
	at org.openimaj.image.model.pixel.HistogramPixelModel.classifyPixel(HistogramPixelModel.java:79)
	at org.openimaj.image.model.pixel.HistogramPixelModel.classifyPixel(HistogramPixelModel.java:44)
	at org.openimaj.image.model.pixel.PixelClassificationModel.classifyImage(PixelClassificationModel.java:62)
	at org.openimaj.image.model.pixel.PixelClassificationModel.predict(PixelClassificationModel.java:88)
	at org.openimaj.image.processing.face.detection.SandeepFaceDetector.generateSkinColorMap(SandeepFaceDetector.java:130)
	at org.openimaj.image.processing.face.detection.SandeepFaceDetector.detectFaces(SandeepFaceDetector.java:209)

I've tried processing several images through it with the following code and get the same exact exception:

        SandeepFaceDetector sandeep = new SandeepFaceDetector();
        try {
            sandeep.detectFaces(ImageUtilities.readMBF(new URL("http://sims.ess.ucla.edu/people-images/2008_Dec_group.JPG")));
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(MyClass.class.getName()).log(Level.SEVERE, null, ex);
        }

**Comment by asaladino** [comment]
You seem to be missing a MBFPixelClassificationModel in your SandeepFaceDetector constructor. The MBFPixelClassificationModel is an abstract class so you will need to implement it or use an already available class like HistogramPixelModel:

https://github.com/openimaj/openimaj/search?utf8=✓&q=MBFPixelClassificationModel&type=Code

Your code might look like this:

MBFPixelClassificationModel skinModel = new HistogramPixelModel(16, 6);
SandeepFaceDetector sandeep = new SandeepFaceDetector(skinModel);
try {
    List stuff = sandeep.detectFaces(ImageUtilities.readMBF(new URL("http://sims.ess.ucla.edu/people-images/2008_Dec_group.JPG")));
    System.out.println("found: " + stuff.size());
} catch (Exception ex) {
    java.util.logging.Logger.getLogger(getClass().getName()).log(Level.SEVERE, null, ex);
}
