### ISSUE TITLE
writing MBFImage to file

### ISSUE THREAD

**Issue by ahsandar** [openimaj/openimaj#91]
trying to write MBFImage to file in scala, but getting exception , code and stacktrace below, 

```
frame.drawShape(face.getBounds(), RGBColour.RED)
       val outputFile: File = new File(f"$opsDetectedPath/$frameName%s.jpg")
       ImageUtilities.write(frame, outputFile)
```

```
java.util.ServiceConfigurationError: javax.imageio.spi.ImageWriterSpi: Provider com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriterSpi could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232) ~[na:1.8.0_45]
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185) ~[na:1.8.0_45]
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384) ~[na:1.8.0_45]
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[na:1.8.0_45]
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[na:1.8.0_45]
        at javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:210) ~[na:1.8.0_45]
        at javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:138) ~[na:1.8.0_45]
        at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:159) ~[na:1.8.0_45]
        at javax.imageio.ImageIO.<clinit>(ImageIO.java:66) ~[na:1.8.0_45]
        at org.openimaj.image.ImageUtilities.write(ImageUtilities.java:273) ~[core-image-1.3.1.jar:na]
```

**Comment by ahsandar** [comment]
is there some other way of writing MBFImages to file?

**Comment by jonhare** [comment]
Almost certainly means that something is missing from the class path - I'm not sure what though... 

Workarounds: 
Try writing to a different format - ie png
Use imageutilities to convert to bufferedimage and save with imageio

**Comment by ahsandar** [comment]
writing in png throws following exception

````
java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO
```

**Comment by ahsandar** [comment]
converting to BufferedImage and trying to wrtie causes the same issues, any suggestions

(http://stackoverflow.com/questions/15345769/exception-when-trying-to-save-images)
(http://stackoverflow.com/questions/7051603/jai-vendorname-null)

**Comment by haraldk** [comment]
Related: https://github.com/haraldk/TwelveMonkeys/issues/167
Seems to be an sbt vs Maven dependency scope issue. 

-- 
Harald K

**Comment by ahsandar** [comment]
thanks @jonhare  and @haraldk , for future reference for those who come across this issue, Add following dependencies and use the following code to write Image files to disk

```

libraryDependencies ++= Seq("com.twelvemonkeys.imageio" % "imageio" % "3.1.2",
                        "com.twelvemonkeys.imageio" % "imageio-core" % "3.1.2",
                        "com.twelvemonkeys.imageio" % "imageio-jpeg" % "3.1.2",
                        "com.twelvemonkeys.common" % "common-lang" % "3.1.2")
```
```
 val bufferedFrame: BufferedImage = ImageUtilities.createBufferedImageForDisplay(frame)
       val outputFile: File = new File("path/to/file.ext")
       ImageIO.write(bufferedFrame, "jpg", outputFile)
```

**Comment by praveendvd** [comment]
New method:

Just use this line 

`ImageUtilities.write(image, new File("2.png"));`
